# Script to train a Nenya model on the 98% cloud free VIIRS data
#  using v4 model
# kubectl exec -it test-pod -- /bin/bash
apiVersion: batch/v1
kind: Job
metadata:
  name: xavier-nenya-swot-l3-train
spec:
  backoffLimit: 0
  template:
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: NotIn
                values:
                  - k8s-chase-ci-01.noc.ucsb.edu
              - key: nvidia.com/gpu.product
                operator: In
                values:
                  - NVIDIA-A10
      containers:
      - name: container
        image: profxj/ihop_nvidia:latest  # On docker hub
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "8"   # Using ~3
            memory: "24Gi"  # Using 5 and climbing..
            ephemeral-storage: 50Gi
          limits:
            cpu: "9"
            memory: "32Gi"
            ephemeral-storage: 100Gi
            nvidia.com/gpu:  "4"  # Holding at ~70% usage..
        command: ["/bin/bash", "-c"]
        args:
          - git clone https://github.com/Sea-Meets-the-Stars/wrangler.git;
            cd wrangler;
            git fetch;
            git checkout nasa_ai;
            git pull;
            pip install -e ".[dev]";
            cd ../nenya; 
            git fetch;
            git checkout swot; 
            git pull; 
            pip install -e ".[dev]";
            cd papers/InformationContent/Analysis;
            aws --endpoint http://rook-ceph-rgw-nautiluss3.rook s3 cp s3://viirs/PreProc/SWOT_L3_250m_preproc.h5 ./;
            aws --endpoint http://rook-ceph-rgw-nautiluss3.rook s3 cp s3://viirs/Nenya/models/SWOT_L3/SimCLR_resnet50_lr_0.05_decay_0.0001_bsz_64_temp_0.07_trial_5_cosine_warm/ckpt_epoch_8.pth ./;
            aws --endpoint http://rook-ceph-rgw-nautiluss3.rook s3 cp s3://viirs/Nenya/models/SWOT_L3/SimCLR_resnet50_lr_0.05_decay_0.0001_bsz_64_temp_0.07_trial_5_cosine_warm/learning_curve/SimCLR_resnet50_lr_0.05_decay_0.0001_bsz_64_temp_0.07_trial_5_cosine_warm_losses_train.h5 ./;
            aws --endpoint http://rook-ceph-rgw-nautiluss3.rook s3 cp s3://viirs/Nenya/models/SWOT_L3/SimCLR_resnet50_lr_0.05_decay_0.0001_bsz_64_temp_0.07_trial_5_cosine_warm/learning_curve/SimCLR_resnet50_lr_0.05_decay_0.0001_bsz_64_temp_0.07_trial_5_cosine_warm_losses_valid.h5 ./;
            sleep 300;
            python -u py/nenya_SWOT_L3.py train;
            aws --endpoint http://rook-ceph-rgw-nautiluss3.rook s3 cp models s3://viirs/Nenya/models --recursive --force;
        env:
          - name: "ENDPOINT_URL"
            value: "http://rook-ceph-rgw-nautiluss3.rook"
          - name: "S3_ENDPOINT"
            value: "rook-ceph-rgw-nautiluss3.rook"
        volumeMounts:
          - name: prp-s3-credentials
            mountPath: "/home/jovyan/.aws/credentials"
            subPath: "credentials"
          - name: ephemeral
            mountPath: "/tmp"
          - name: "dshm"
            mountPath: "/dev/shm"
      restartPolicy: Never
      volumes:
        # Secrets file for nautilus s3 credentials .aws/credentials and .s3cfg
        - name: prp-s3-credentials
          secret:
            secretName: prp-s3-credentials
        # Shared memory (necessary for Python's multiprocessing.shared_memory module to work)
        - name: dshm
          emptyDir:
            medium: Memory
        # Ephemeral storage
        - name: ephemeral
          emptyDir: {}
